BullyAssure/Models/Settings/Setting.cs
using DatabaseConnector.Tables.Settings;

namespace BullyAssure.Models.Settings
{
  public class Settings : Setting
  {
  }
}

BullyAssure/Components/BreederFieldViewComponent.cs
using DatabaseConnector;
using DatabaseConnector.Tables.Breeders;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BullyAssure.Components
{
  public class BreederFieldViewComponent : ViewComponent
  {
    private readonly BullyAssureContext db;

    public BreederFieldViewComponent(BullyAssureContext context)
    {
      db = context;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
      var items = await GetBreederPageFieldAsync();
      return View(items);
    }

    private Task<List<BreederPageField>> GetBreederPageFieldAsync()
    {
      var UserID = HttpContext.Session.GetString("UserID");
      return db.BreederPageFields.Include(e => e.FieldType).Where(e => !e.isDeleted).ToListAsync();
    }
  }
}

BullyAssure/Components/FieldTypeViewComponent.cs
using DatabaseConnector;
using DatabaseConnector.Tables.Fields;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BullyAssure.Components
{
  public class FieldTypeViewComponent : ViewComponent
  {
    private readonly BullyAssureContext db;

    public FieldTypeViewComponent(BullyAssureContext context)
    {
      db = context;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
      var items = await GetPageFieldAsync();
      return View(items);
    }

    private Task<List<FieldType>> GetPageFieldAsync()
    {
      var UserID = HttpContext.Session.GetString("UserID");
      return db.FieldTypes.Where(e => !e.isDeleted).ToListAsync();
    }
  }
}

BullyAssure/Components/KennelFieldViewComponent.cs
using DatabaseConnector;
using DatabaseConnector.Tables.Kennels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BullyAssure.Components
{
  public class KennelFieldViewComponent : ViewComponent
  {
    private readonly BullyAssureContext db;

    public KennelFieldViewComponent(BullyAssureContext context)
    {
      db = context;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
      var items = await GetKennelPageFieldAsync();
      return View(items);
    }

    private Task<List<KennelPageField>> GetKennelPageFieldAsync()
    {
      var UserID = HttpContext.Session.GetString("UserID");
      return db.KennelPageFields.Include(e => e.FieldType).Where(e => !e.isDeleted).ToListAsync();
    }
  }
}

BullyAssure/Components/PermissionsViewComponent.cs
using DatabaseConnector;
using DatabaseConnector.Tables.Users;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BullyAssure.Components
{
  public class PermissionsViewComponent : ViewComponent
  {
    private readonly BullyAssureContext db;

    public PermissionsViewComponent(BullyAssureContext context)
    {
      this.db = context;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
      var items = await GetUsersAsync();
      return View(items);
    }

    private Task<List<UserMain>> GetUsersAsync()
    {
      var UserID = HttpContext.Session.GetString("UserID");
      return db.Users
        .Include(e => e.OrgStructure)
          .ThenInclude(e => e.ParentStructure)
          .Include(e => e.UserPermission)
        .Where(e => e.UserID != Guid.Parse(UserID))
        .ToListAsync();
    }
  }
}

BullyAssure/Controllers/SettingsController.cs
using ApplicationWorkers.Communications;
using BullyAssure.Filters;
using DatabaseConnector;
using DatabaseConnector.Tables.Breeders;
using DatabaseConnector.Tables.Configuration;
using DatabaseConnector.Tables.Kennels;
using DatabaseConnector.Tables.Owners;
using DatabaseConnector.Tables.Pedigrees;
using DatabaseConnector.Tables.Permissions;
using DatabaseConnector.Tables.Settings;
using DatabaseConnector.Tables.Users;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace BullyAssure.Controllers
{
  public class SettingsController : Controller
  {
    private BullyAssureContext db;
    private IConfiguration config;
    private readonly EmailHandler emailHandler;

    public SettingsController(BullyAssureContext _db, IConfiguration _config, EmailHandler _emailHandler)
    {
      this.db = _db;
      this.config = _config;
      this.emailHandler = _emailHandler;
    }

    [ControllerActionFilter]
    [HttpGet]
    public IActionResult Index()
    {
      try
      {
        var UserID = HttpContext.Session.GetString("UserID");
        var user = this.db.Users.Include(f => f.UserPermission).FirstOrDefault(e => e.UserID == Guid.Parse(UserID));
        ViewData["User"] = user;

        return View("Index");
      }
      catch (Exception ex)
      {
        LogFilter.Write(db, HttpContext.Request.QueryString.ToString(), HttpContext.Request.Path, HttpContext.Session.GetString("UserID"), ex);
        return View("Error", ex);
      }
    }

    [ControllerActionFilter]
    [HttpGet]
    public IActionResult Create()
    {
      try
      {
        return View("Create", new Setting());
      }
      catch (Exception ex)
      {
        LogFilter.Write(db, HttpContext.Request.QueryString.ToString(), HttpContext.Request.Path, HttpContext.Session.GetString("UserID"), ex);
        return View("Error", ex);
      }
    }

    [ControllerActionFilter]
    [HttpPost]
    public IActionResult SaveNewSetting(Setting SettingDetails)
    {
      try
      {
        db.Settings.Add(SettingDetails);
        db.SaveChanges();

        db.PermissionsStructures.Add(new PermissionsStructure
        {
          OrgStructureID = db.OrgStructures.FirstOrDefault(e => e.StructureID == (db.Users.FirstOrDefault(u => u.UserID == Guid.Parse(HttpContext.Session.GetString("UserID"))).OrgStructureID)).StructureID,
          Path = SettingDetails.To,
          PermissionName = $"{SettingDetails.SettingNavName} View"
        });

        db.SaveChanges();

        try
        {
          emailHandler.SendEmail(
                ToAddresses: new List<string> { "vbester3@gmail.com" },
                Subject: $"Bully Assure: New Setting",
                Body: $"Good Day <br />" +
                $"<br /> " +
                $"<br /> {db.Users.FirstOrDefault(u => u.UserID == Guid.Parse(HttpContext.Session.GetString("UserID"))).Firstname} added new Setting - {SettingDetails.SettingNavName} View" +
                $"<br /> If you are not aware of this, please contact System Administrator on <a href=\"mailto:{JsonSerializer.Deserialize<SystemConfiguration>(HttpContext.Session.GetString("SYSTEMCONFIGURATION")).UserName}\">System Admin</a>." +
                $"<br /> " +
                $"<br />" +
                $"<br /> Kind Regards," +
               $"<br /> <a href=\"{JsonSerializer.Deserialize<SystemConfiguration>(HttpContext.Session.GetString("SYSTEMCONFIGURATION")).WebsiteUrl}\">Bully Assure System</a>",
                AttachmentsBinaries: null,
                UserID: HttpContext.Session.GetString("UserID"),
                systemConfiguration: JsonSerializer.Deserialize<SystemConfiguration>(HttpContext.Session.GetString("SYSTEMCONFIGURATION"))
                );
        }
        catch (Exception)
        {
        }

        return RedirectToAction("Index", "Settings");
      }
      catch (Exception ex)
      {
        LogFilter.Write(db, HttpContext.Request.QueryString.ToString(), HttpContext.Request.Path, HttpContext.Session.GetString("UserID"), ex);
        return View("Error", ex);
      }
    }

    [ControllerActionFilter]
    [HttpGet]
    public IActionResult Delete(Guid SettingID)
    {
      try
      {
        var UserID = HttpContext.Session.GetString("UserID");

        if (!db.Users.Include(g => g.UserPermission).Any(f => f.UserID == Guid.Parse(UserID) && f.UserPermission.EditMenuNav))
        {
          return RedirectToAction("Index", "Settings");
        }
        var Settings = db.Settings.FirstOrDefault(e => e.ID == SettingID);
        Settings.isDeleted = true;
        db.Settings.Update(Settings);
        db.SaveChanges();

        try
        {
          emailHandler.SendEmail(
                ToAddresses: new List<string> { "vbester3@gmail.com" },
                Subject: $"Bully Assure: Deleted Setting",
                Body: $"Good Day <br />" +
                $"<br /> " +
                $"<br /> {db.Users.FirstOrDefault(u => u.UserID == Guid.Parse(HttpContext.Session.GetString("UserID"))).Firstname} deleted Setting - {Settings.SettingNavName} View" +
                $"<br /> If you are not aware of this, please contact System Administrator on <a href=\"mailto:{JsonSerializer.Deserialize<SystemConfiguration>(HttpContext.Session.GetString("SYSTEMCONFIGURATION")).UserName}\">System Admin</a>." +
                $"<br /> " +
                $"<br />" +
                $"<br /> Kind Regards," +
               $"<br /> <a href=\"{JsonSerializer.Deserialize<SystemConfiguration>(HttpContext.Session.GetString("SYSTEMCONFIGURATION")).WebsiteUrl}\">Bully Assure System</a>",
                AttachmentsBinaries: null,
                UserID: HttpContext.Session.GetString("UserID"),
                systemConfiguration: JsonSerializer.Deserialize<SystemConfiguration>(HttpContext.Session.GetString("SYSTEMCONFIGURATION"))
                );
        }
        catch (Exception)
        {
        }

        return RedirectToAction("Index", "Settings");
      }
      catch (Exception ex)
      {
        LogFilter.Write(db, HttpContext.Request.QueryString.ToString(), HttpContext.Request.Path, HttpContext.Session.GetString("UserID"), ex);
        return View("Error", ex);
      }
    }

    [ControllerActionFilter]
    [HttpPost]
    public async Task<IActionResult> SaveSystemSettings(SystemConfiguration systemConfiguration)
    {
      try
      {
        if (systemConfiguration != null)
        {
          this.db.SystemConfigurations.Update(systemConfiguration);
          await this.db.SaveChangesAsync();
        }

        try
        {
          emailHandler.SendEmail(
                ToAddresses: new List<string> { "vbester3@gmail.com" },
                Subject: $"Bully Assure: Updated System Settings",
                Body: $"Good Day <br />" +
                $"<br /> " +
                $"<br /> {db.Users.FirstOrDefault(u => u.UserID == Guid.Parse(HttpContext.Session.GetString("UserID"))).Firstname} updated System Settings" +
                $"<br /> If you are not aware of this, please contact System Administrator on <a href=\"mailto:{JsonSerializer.Deserialize<SystemConfiguration>(HttpContext.Session.GetString("SYSTEMCONFIGURATION")).UserName}\">System Admin</a>." +
                $"<br /> " +
                $"<br />" +
                $"<br /> Kind Regards," +
               $"<br /> <a href=\"{JsonSerializer.Deserialize<SystemConfiguration>(HttpContext.Session.GetString("SYSTEMCONFIGURATION")).WebsiteUrl}\">Bully Assure System</a>",
                AttachmentsBinaries: null,
                UserID: HttpContext.Session.GetString("UserID"),
                systemConfiguration: JsonSerializer.Deserialize<SystemConfiguration>(HttpContext.Session.GetString("SYSTEMCONFIGURATION"))
                );
        }
        catch (Exception)
        {
        }

        return RedirectToAction("Index", "Settings");
      }
      catch (Exception ex)
      {
        LogFilter.Write(db, HttpContext.Request.QueryString.ToString(), HttpContext.Request.Path, HttpContext.Session.GetString("UserID"), ex);
        return View("Error", ex);
      }
    }

    #region Kennel Fields

    [ControllerActionFilter]
    [HttpGet]
    public IActionResult CreateKennelField()
    {
      try
      {
        return View("CreateKennelField", new KennelPageField());
      }
      catch (Exception ex)
      {
        LogFilter.Write(db, HttpContext.Request.QueryString.ToString(), HttpContext.Request.Path, HttpContext.Session.GetString("UserID"), ex);
        return View("Error", ex);
      }
    }

    [ControllerActionFilter]
    [HttpPost]
    public IActionResult SaveKennelField(KennelPageField kennelPageField)
    {
      try
      {
        if (kennelPageField != null)
        {
          db.KennelPageFields.Update(kennelPageField);
          db.SaveChanges();
        }

        try
        {
          emailHandler.SendEmail(
                ToAddresses: new List<string> { "vbester3@gmail.com" },
                Subject: $"Bully Assure: New Kennel Field",
                Body: $"Good Day <br />" +
                $"<br /> " +
                $"<br /> {db.Users.FirstOrDefault(u => u.UserID == Guid.Parse(HttpContext.Session.GetString("UserID"))).Firstname} added new kennel field - {kennelPageField.FieldName} View" +
                $"<br /> If you are not aware of this, please contact System Administrator on <a href=\"mailto:{JsonSerializer.Deserialize<SystemConfiguration>(HttpContext.Session.GetString("SYSTEMCONFIGURATION")).UserName}\">System Admin</a>." +
                $"<br /> " +
                $"<br />" +
                $"<br /> Kind Regards," +

BullyAssure/Views/Settings/Create.cshtml
@model DatabaseConnector.Tables.Settings.Setting
@{
    ViewData["Title"] = "Create New Nav Setting";
}
<div class="row">
    <div class="col-md-4">
        <form asp-action="SaveNewSetting">
            @Html.HiddenFor(m => m.ID)
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Setting Name</label>
                <input asp-for="SettingName" class="form-control" />
                <span asp-validation-for="SettingName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Order</label>
                <input asp-for="Order" type="number" class="form-control" />
                <span asp-validation-for="Order" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">To</label>
                <input asp-for="To" class="form-control" />
                <span asp-validation-for="To" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Action</label>
                <input asp-for="Action" class="form-control" />
                <span asp-validation-for="Action" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Setting Nav Name</label>
                <input asp-for="SettingNavName" class="form-control" />
                <span asp-validation-for="SettingNavName" class="text-danger"></span>
            </div>
            <div class="form-group">
              <input type="submit" value="Save" class="btn btn-primary p-1" />
              <a class="btn btn-secondary p-1" asp-action="Index">Cancel</a>
            </div>
        </form>
    </div>
</div>

BullyAssure/Views/Settings/CreateBreederField.cshtml
@model DatabaseConnector.Tables.Breeders.BreederPageField
@{
  ViewData["Title"] = "Breeder Field";
}
<h4>New Breeder Field</h4>
<hr />
<div class="row">
  <div class="col-md-4">
    <form asp-action="SaveBreederField">
      <div asp-validation-summary="ModelOnly" class="text-danger"></div>
      <div class="form-group">
        <label asp-for="FieldTypeID" class="control-label"></label>
        @await Component.InvokeAsync("FieldType")
        <span asp-validation-for="FieldTypeID" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="FieldName" class="control-label"></label>
        <input asp-for="FieldName" class="form-control" />
        <span asp-validation-for="FieldName" class="text-danger"></span>
      </div>
      <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary p-1" />
        <input type="button" value="Cancel" asp-action="Index" onclick="window.location.href = '/Settings'" class="btn btn-secondary p-1" />
      </div>
    </form>
  </div>
</div>

BullyAssure/Views/Settings/CreateKennelField.cshtml
@model DatabaseConnector.Tables.Kennels.KennelPageField
@{
  ViewData["Title"] = "Kennel Field";
}
<h4>New Kennel Field</h4>
<hr />
<div class="row">
  <div class="col-md-4">
    <form asp-action="SaveKennelField">
      <div asp-validation-summary="ModelOnly" class="text-danger"></div>
      <div class="form-group">
        <label asp-for="FieldTypeID" class="control-label"></label>
        @await Component.InvokeAsync("FieldType")
        <span asp-validation-for="FieldTypeID" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="FieldName" class="control-label"></label>
        <input asp-for="FieldName" class="form-control" />
        <span asp-validation-for="FieldName" class="text-danger"></span>
      </div>
      <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary p-1" />
        <input type="button" value="Cancel" asp-action="Index" onclick="window.location.href = '/Settings'" class="btn btn-secondary p-1" />
      </div>
    </form>
  </div>
</div>

BullyAssure/Views/Settings/CreateOwnerField.cshtml
@model DatabaseConnector.Tables.Owners.OwnerPageField
@{
  ViewData["Title"] = "Owner Field";
}
<h4>New Owner Field</h4>
<hr />
<div class="row">
  <div class="col-md-4">
    <form asp-action="SaveOwnerField">
      <div class="form-group">
        <label asp-for="FieldTypeID" class="control-label"></label>
        @await Component.InvokeAsync("FieldType")
        <span asp-validation-for="FieldTypeID" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="FieldName" class="control-label"></label>
        <input asp-for="FieldName" class="form-control" />
        <span asp-validation-for="FieldName" class="text-danger"></span>
      </div>
      <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary p-1" />
        <input type="button" value="Cancel" asp-action="Index" onclick="window.location.href = '/Settings'" class="btn btn-secondary p-1" />
      </div>
    </form>
  </div>
</div>

BullyAssure/Views/Settings/CreatePedigreeField.cshtml
@model DatabaseConnector.Tables.Pedigrees.PedigreePageField
@{
  ViewData["Title"] = "Pedigree Field";
}
<h4>New Pedigree Field</h4>
<hr />
<div class="row">
  <div class="col-md-4">
    <form asp-action="SavePedigreeField">
      <div asp-validation-summary="ModelOnly" class="text-danger"></div>
      <div class="form-group">
        <label asp-for="FieldTypeID" class="control-label"></label>
        @await Component.InvokeAsync("FieldType")
        <span asp-validation-for="FieldTypeID" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="FieldName" class="control-label"></label>
        <input asp-for="FieldName" class="form-control" />
        <span asp-validation-for="FieldName" class="text-danger"></span>
      </div>
      <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary p-1" />
        <input type="button" value="Cancel" asp-action="Index" onclick="window.location.href = '/Settings'" class="btn btn-secondary p-1" />
      </div>
    </form>
  </div>
</div>

BullyAssure/Views/Settings/Index.cshtml
@{
  ViewData["Title"] = "Settings Page";

  DatabaseConnector.Tables.Users.UserMain userMain = (DatabaseConnector.Tables.Users.UserMain)ViewData["User"];

}
<ul class="nav nav-tabs" style="margin: 19px 0px 18px; visibility: visible;">
  @if (userMain.UserPermission.EditMenuNav)
  {
    <li><a data-toggle="tab" class="btn btn-primary p-1" aria-expanded="true" href="#menu">Menu Navigation</a></li>
  }
  @if (userMain.UserPermission.EditKennelFields)
  {
    <li><a data-toggle="tab" class="btn btn-primary p-1" aria-expanded="true" href="#kennelfields">Kennel Fields</a></li>
  }
  @if (userMain.UserPermission.EditBreederFields)
  {
    <li><a data-toggle="tab" class="btn btn-primary p-1" aria-expanded="true" href="#breederfields">Breeder Fields</a></li>
  }
  @if (userMain.UserPermission.EditPedigreeFields)
  {
    <li><a data-toggle="tab" class="btn btn-primary p-1" aria-expanded="true" href="#pedigreefields">Pedigree Fields</a></li>
  }
  @if (userMain.UserPermission.EditGlobalSettings)
  {
    <li><a data-toggle="tab" class="btn btn-primary p-1" aria-expanded="true" href="#globalsettings">Global Settings</a></li>
  }
  @if (userMain.UserPermission.EditPermissions)
  {
    <li><a data-toggle="tab" class="btn btn-primary p-1" aria-expanded="true" href="#userpermissions">User Permissions</a></li>
  }
  @if (userMain.isDeveloper)
  {
    <li><a data-toggle="tab" class="btn btn-primary p-1" aria-expanded="true" href="#systemsettings">System Settings</a></li>
    <li><a data-toggle="tab" class="btn btn-primary p-1" aria-expanded="true" href="#loggingfields">Application Logs</a></li>
  }
</ul>

<div class="tab-content">
  @if (userMain.UserPermission.EditMenuNav)
  {
    <div id="menu" class="tab-pane fade">
      <h3>Menu Navigation</h3>
      @await Component.InvokeAsync("SettingsMenuNav")
    </div>
  }

  @if (userMain.UserPermission.EditKennelFields)
  {
    <div id="kennelfields" class="tab-pane fade">
      <h3>Kennel Fields</h3>
      @await Component.InvokeAsync("KennelField")
    </div>
  }

  @if (userMain.UserPermission.EditBreederFields)
  {
    <div id="breederfields" class="tab-pane fade">
      <h3>Breeder Fields</h3>
      @await Component.InvokeAsync("BreederField")
    </div>
  }

  @if (userMain.UserPermission.EditPedigreeFields)
  {
    <div id="pedigreefields" class="tab-pane fade">
      <h3>Pedigree Fields</h3>
      @await Component.InvokeAsync("PedigreeFields")
    </div>
  }

  @if (userMain.UserPermission.EditGlobalSettings)
  {
    <div id="globalsettings" class="tab-pane fade">
      <h3>Global Settings</h3>
      @await Component.InvokeAsync("GlobalSettings")
    </div>
  }

  @if (userMain.isAdmin)
  {
    <div id="userpermissions" class="tab-pane fade">
      <h3>User Permissions</h3>
      @await Component.InvokeAsync("Permissions")
    </div>
  }

  @if (userMain.isDeveloper)
  {
    <div id="userpermissions" class="tab-pane fade">
      <h3>User Permissions</h3>
      @await Component.InvokeAsync("Permissions")
    </div>
    <div id="systemsettings" class="tab-pane fade">
      <h3>System Configurations</h3>
      @await Component.InvokeAsync("SystemSettings")
    </div>
    <div id="loggingfields" class="tab-pane fade">
      <h3>Application Logs</h3>
      @await Component.InvokeAsync("Error")
    </div>
  }
</div>

<script>
  $("li").on("click", function () {
    $("li").each(function () {
      $(this).removeClass("active");
    });
    $(this).addClass("active");
  });
</script>